# Generated by Django 6.0 on 2026-01-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='test',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
