# Generated by Django 6.0 on 2026-01-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0002_perfil_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='test',
        ),
    ]
