# Generated by Django 6.0.1 on 2026-01-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0004_alter_experiencialaboral_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacion',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='recomendacion',
            old_name='cargo',
            new_name='nombre_contacto',
        ),
        migrations.RenameField(
            model_name='recomendacion',
            old_name='nombre_quien_recomienda',
            new_name='parentesco_o_relacion',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='telefono_contacto',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('ACADEMICO', 'Académico'), ('LABORAL', 'Laboral')], max_length=20),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('horas_duracion', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='pagina_usuario.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha_graduacion', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='pagina_usuario.perfil')),
            ],
        ),
    ]
