# Generated by Django 6.0.1 on 2026-01-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0005_rename_texto_recomendacion_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='horas_duracion',
            new_name='total_horas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_obtencion',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='fecha_graduacion',
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='link',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='parentesco_o_relacion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='archivo',
        ),
        migrations.AddField(
            model_name='curso',
            name='entidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='graduado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='relacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default='exit', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion_domicilio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='telefono_contacto',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='pagina_usuario.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperienciaLaboral',
        ),
    ]
