# Generated by Django 4.2.27 on 2026-01-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0006_rename_horas_duracion_curso_total_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='educacion',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('En progreso', 'En progreso'), ('No completado', 'No completado')], default='Completado', max_length=20),
        ),
        migrations.AddField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='puesto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados_recomendaciones/'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
