# Generated by Django 4.2.27 on 2026-01-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0007_curso_activo_curso_certificado_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='recomendacion',
            options={'verbose_name': 'Recomendación', 'verbose_name_plural': 'Recomendaciones'},
        ),
        migrations.AddField(
            model_name='curso',
            name='email_empresa_patrocinadora',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_contacto_auspicia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='telefono_contacto_auspicia',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='email_empresa',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de la empresa'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='lugar_empresa',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lugar de la empresa'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre_contacto_empresarial',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='sitio_web_empresa',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sitio web de empresa'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='telefono_contacto_empresarial',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Perfil activo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Descripción del perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion_trabajo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_convencional',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='productos',
            name='clasificador',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='entidad_patrocinadora',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='fecha_reconocimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='tipo_reconocimiento',
            field=models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entidad patrocinadora'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo (Académico o Laboral)'),
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_bien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='pagina_usuario.perfil')),
            ],
            options={
                'verbose_name': 'Venta Garage',
                'verbose_name_plural': 'Ventas Garage',
            },
        ),
    ]
