# Generated by Django 4.2.27 on 2026-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0008_alter_curso_options_alter_educacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='resumen_profesional',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
